version: '3.7'
services:
  accounts-db:
    image: postgres:9.6.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=accounts
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin